### ISSUE TITLE
Rounded Corners in Monaco Editor

### ISSUE THREAD

**Issue by dhrubajyotifounderofDSoft** [DSoftofficial/Tilder-web-app#15]
`border-radius` is not working with the Monaco-Editor in [App.css file](https://github.com/DSoftofficial/Tilder-web-app/blob/main/web-app/src/App.css)

```
.editor-wrapper{
    display: flex;
    justify-content: flex-end;
    align-items: flex-end;
    border-radius: 4px;
}
```

**Comment by noorhashem77** [comment]
Yep i'm having the same issue as well.

**Comment by noorhashem77** [comment]
Hey @dhrubajyotifounderofDSoft  this worked for me.

`.editor-wrapper .monaco-editor,
.editor-wrapper .overflow-guard {
    border-radius: 10px;
}`

**Comment by dhrubajyotifounderofDSoft** [comment]
https://stackoverflow.com/questions/68928037/change-inlay-hints-style-in-monaco-editor

I also read this.

**Comment by dhrubajyotifounderofDSoft** [comment]
But thanks @noorhashem77

**Comment by dhrubajyotifounderofDSoft** [comment]
@noorhashem77 I solved the problem, if we add this CSS:

```
.overflow-guard{
    border-radius: 10px;
}
```

**Comment by mohd-khan09** [comment]
wer can i fimd this styles to edit this??
