### ISSUE TITLE
Monaco-Editor

### ISSUE THREAD

**Issue by Dhrubajyo** [DSoftofficial/Tilder-web-app#6]
Monaco - The Editor of the Web

The Monaco Editor is the code editor that powers [VS Code](https://github.com/microsoft/vscode). A good page describing the code editor's features is [here](https://code.visualstudio.com/docs/editor/editingevolved). It is licensed under the MIT License and supports Edge, Chrome, Firefox, Safari and Opera. The Monaco editor is not supported in mobile browsers or mobile web frameworks. Find more information at the [Monaco Editor repo](https://github.com/microsoft/monaco-editor).Tilder's code-editor will be powered by Monaco-Editor

**Comment by dhrubajyotifounderofDSoft** [comment]
I have committed to Tilder we-app the Monaco Editor using Vite + React
